film_accueil :
    path: /accueil
    controller : App\Controller\FilmController::accueil

film_afficher :
    path: /afficher/{id}
    controller: App\Controller\FilmController::afficher

film_ajouter : 
    path: /ajouter
    controller: App\Controller\FilmController::ajouter

film_modifier : 
    path: /modifier/{id}
    controller: App\Controller\FilmController::modifier

film_modifier_suite : 
    path: /modifier_suite/{id}
    controller: App\Controller\FilmController::modifierSuite
    methods: POST

film_supprimer : 
    path: /supprimer/{id}
    controller: App\Controller\FilmController::supprimer

film_filtre : 
    path: /filtre
    controller: App\Controller\FilmController:filtre